### PR TITLE
Updated User stories in DG

### PR DESCRIPTION
**Pull request by Pinran-J**

### CODE REVIEW

**Comment by rui-han-crh** [comment]
LGTM, can merge when everyone's ready

**Review by rui-han-crh — APPROVED** [review]

**Review by ryanczx — APPROVED** [review]
LGTM, can merge when everyone's ready

**Comment by Neethesh26** [comment]
LGTM

**Review by Neethesh26 — APPROVED** [review]
LGTM

**Review by czhongwei — APPROVED** [review]
LGTM

**Pull request merged**
