### PR TITLE
Add ryan chua info

### PR DESCRIPTION
**Pull request by ryanczx**
- Add profile photo for Ryan: images/ryanczx.png
- About.md: Update image link for Ryan
- About.md: Update github link for Ryan

### CODE REVIEW

**Comment by czhongwei** [comment]
LGTM my g

**Comment by rui-han-crh** [comment]
Looks good

**Review by rui-han-crh — APPROVED** [review]
Approved

**Review by czhongwei — APPROVED** [review]
LGTM

**Pull request merged**
