### PR TITLE
Fix 2 images find86result.png and findAlexDavidResult.png

### PR DESCRIPTION
**Pull request by czhongwei**

### CODE REVIEW

**Comment by rui-han-crh** [comment]
Should we include the already executed command again in the command box in the picture or should we leave it blank and just point out that this is the result of the execution

**Comment by ryanczx** [comment]
> Should we include the already executed command again in the command box in the picture or should we leave it blank and just point out that this is the result of the execution

I think we should just leave the command box blank because the command entered is already listed above it. For example: 
`find alex david` returns `Alex Yeoh`, `David Li`

**Review by ryanczx — APPROVED** [review]
lgtm

**Comment by rui-han-crh** [comment]
> @ryanczx 

okay

**Review by rui-han-crh — APPROVED** [review]

**Pull request merged**
