### PR TITLE
Update UserGuide.md to include changes to find command

### PR DESCRIPTION
**Pull request by czhongwei**
- Remove findlidResult.png as it was obsolete
- Add find64result.png to UserGuide under `find` section
- Update `find` section to reflect new changes

### CODE REVIEW

**Comment by rui-han-crh** [comment]
Do you wanna use Ryan's suggestion #60 on `startsWith` search for phone numbers over the `contains` substring match, so it would be `find 86` instead of `find 64`?

**Review by rui-han-crh — APPROVED** [review]
lgtm

**Review by ryanczx — APPROVED** [review]
lgtm

**Review by Neethesh26 — APPROVED** [review]
lgtm

**Pull request merged**
