### PR TITLE
Update HelpWindow.java UserGuide link

### LINKED ISSUE #56: Update help command
We need to update the help command to give the link to [https://ay2223s1-cs2103t-w12-2.github.io/tp/UserGuide.html](https://ay2223s1-cs2103t-w12-2.github.io/tp/UserGuide.html) instead of the AB3 website.

### PR DESCRIPTION
**Pull request by ryanczx**
Update HelpWindow.java to use SectresBook's User Guide link instead of AB3's User Guide link.

Fixes #56

### CODE REVIEW

**Review by rui-han-crh — APPROVED** [review]
LGTM

**Review by Neethesh26 — APPROVED** [review]
LGTM

**Comment by rui-han-crh** [comment]
Is it possible to take a snippet of the help message window when you type `help` and update the `helpMessage.png` file under `images` also?

**Comment by ryanczx** [comment]
Ok, updated `helpMessage.png`.

**Review by Pinran-J — APPROVED** [review]
LGTM

**Pull request merged**
